import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Text,
  Box,
  Flex,
  Badge,
} from "@chakra-ui/react";

type Price = {
  id: string;
  symbol: string;
  name: string;
  image: string;
  current_price: number;
  price_change_percentage_24h: number;
  total_volume: number;
  market_cap: number;
};

const formatNumber = (num: number) => {
  return Intl.NumberFormat("id-Id").format(num);
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text fontSize="2xl" as="b">
        Crypto Coins Market
      </Text>
      <Box mt={5} boxShadow="base" p="6" rounded="lg" bg="white">
        <Table variant="simple">
          <Thead>
            <Tr>
              <Th>Coin</Th>
              <Th>Last Price</Th>
              <Th>Total Volume</Th>
            </Tr>
          </Thead>
          <Tbody>
            <Tr>
              <Td>
                <Flex alignItems="center">
                  <Image
                    width={24}
                    height={24}
                    alt="Coin Logo"
                    src="https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579"
                  />

                  <Text pl={2} fontWeight="bold" textTransform="capitalize">
                    100000
                  </Text>
                  <Badge ml={3}>100000</Badge>
                </Flex>
              </Td>
              <Td>{formatNumber(100000)}</Td>
              <Td>{formatNumber(100000)}</Td>
            </Tr>
          </Tbody>
        </Table>
      </Box>
    </div>
  );
};

export default Home;
